# Default values for ChromaDB Helm chart

replicaCount: 1

image:
  repository: chromadb/chroma
  tag: "0.6.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8090
  targetPort: 8000

env:
  ALLOW_RESET: "true"
  CHROMA_SERVER_HOST: "0.0.0.0"
  CHROMA_SERVER_HTTP_PORT: "8000"
  IS_PERSISTENT: "true"
  PERSIST_DIRECTORY: "/data"
  ANONYMIZED_TELEMETRY: "false"

persistence:
  enabled: true
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  hostPath:
    enabled: true
    path: /tmp/chromadb-data

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
