primary:
  persistence:
    enabled: true
    size: 10Gi # 기존 8Gi에서 10Gi로 변경

  service:
    type: LoadBalancer # DBeaver 등에서 직접 접근할 수 있도록 변경

  initdbScriptsCM:
    init-config.sql: |
      -- 비밀번호 암호화 방식을 md5로 설정
      ALTER SYSTEM SET password_encryption = 'md5';
      SELECT pg_reload_conf();  -- 설정 적용

      -- postgres 계정의 비밀번호 설정
      ALTER USER postgres WITH PASSWORD 'postgresql';

      -- adminuser 계정이 없으면 생성 후 권한 부여
      DO $$ 
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'adminuser') THEN
          CREATE ROLE adminuser WITH LOGIN PASSWORD 'admin1234';
          ALTER ROLE adminuser CREATEDB;
          CREATE DATABASE ragdb OWNER adminuser;
          GRANT ALL PRIVILEGES ON DATABASE ragdb TO adminuser;
        END IF;
      END $$;

      -- postgres 계정이 ragdb 데이터베이스를 관리할 수 있도록 권한 부여
      GRANT ALL PRIVILEGES ON DATABASE ragdb TO postgres;
      ALTER ROLE adminuser WITH SUPERUSER INHERIT;
      GRANT pg_read_all_settings TO postgres;

  postgresqlConfiguration:
    max_connections: "200"
    shared_buffers: "256MB"

  extendedConfiguration: |
    listen_addresses = '*'
    password_encryption = 'md5'

  pgHbaConfiguration: |
    local   all             postgres                                trust
    local   all             all                                     md5
    host    all             all             127.0.0.1/32            md5
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::1/128                 md5

auth:
  postgresPassword: "postgresql"
  username: "adminuser"
  password: "admin1234"
  database: "ragdb"
