primary:
  persistence:
    size: 10Gi # 기존 8Gi에서 10Gi로 변경
  service:
    type: LoadBalancer # 기존 ClusterIP에서 LoadBalancer로 변경
auth:
  username: airflow # 기본 유저를 airflow에서 myuser로 변경
  password: airflow # 보안 강화를 위해 변경
  database: airflow # 기본 DB 이름 변경
