primary:
  persistence:
    enabled: true
    size: 10Gi # 기존 8Gi에서 10Gi로 변경

  service:
    type: LoadBalancer # DBeaver 등에서 직접 접근할 수 있도록 변경

  initdbScriptsCM:
    init-users.sql: |
      DO $$ 
      BEGIN
        -- airflow 계정이 없으면 생성
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'airflow') THEN
          CREATE ROLE airflow WITH LOGIN PASSWORD 'airflow';
          ALTER ROLE airflow CREATEDB;
          CREATE DATABASE airflow OWNER airflow;
          GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
        END IF;
      END $$;

    init-config.sql: |
      -- 비밀번호 암호화 방식을 md5로 설정
      ALTER SYSTEM SET password_encryption = 'md5';
      SELECT pg_reload_conf();  -- 설정 적용

      -- airflow 계정의 비밀번호를 md5 방식으로 다시 설정
      ALTER USER airflow WITH PASSWORD 'airflow';

  postgresqlConfiguration:
    max_connections: "200"
    shared_buffers: "256MB"

  extendedConfiguration: |
    listen_addresses = '*'
    password_encryption = 'md5'

  pgHbaConfiguration: |
    local   all             postgres                                trust
    local   all             all                                     md5
    host    all             all             127.0.0.1/32            md5
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::1/128                 md5

auth:
  postgresPassword: "newpassword"
  username: "airflow"
  password: "airflow"
  database: "airflow"
