apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-fastapi-github
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ch0992/gitops.git
    targetRevision: HEAD
    path: rag-fastapi-structured/helm
    helm:
      valueFiles:
        - values.yaml
      values: |
        environment:
          name: github
        image:
          repository: ghcr.io/ch0992/rag-fastapi-structured
          tag: latest
          pullPolicy: Always
        service:
          port: 9001
        imagePullSecrets:
          - name: ghcr-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
