apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: {{ .Release.Name }}-qdrant
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-qdrant
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-qdrant
    spec:
      containers:
      - name: qdrant
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        - containerPort: {{ .Values.service.grpcPort }}
          name: grpc
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - name: qdrant-data
          mountPath: {{ .Values.env.QDRANT__STORAGE__STORAGE_PATH }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: qdrant-data
        {{- if and .Values.persistence.enabled .Values.persistence.hostPath.enabled }}
        hostPath:
          path: {{ .Values.persistence.hostPath.path }}
          type: DirectoryOrCreate
        {{- else if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-qdrant-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
