{{- if and .Values.persistence.enabled .Values.persistence.hostPath.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "lmstudio.fullname" . }}
  labels:
    {{- include "lmstudio.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
{{- end }}