apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lmstudio.fullname" . }}
  labels:
    {{- include "lmstudio.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}