environment:
  name: local

replicaCount: 1

image:
  repository: rag-fastapi-structured
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

probes:
  livenessProbe:
    httpGet:
      path: /
      port: 8000
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /
      port: 8000
    initialDelaySeconds: 60
    periodSeconds: 5
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 12
