# Custom values for Qdrant Helm chart

replicaCount: 1

image:
  repository: docker.io/qdrant/qdrant
  pullPolicy: IfNotPresent
  # Specify a proper semantic version
  tag: "1.13.4"
  useUnprivilegedImage: true

service:
  type: LoadBalancer
  ports:
  - name: http
    port: 8050
    targetPort: 6333
    protocol: TCP
    checksEnabled: true
  - name: grpc
    port: 8051
    targetPort: 6334
    protocol: TCP
    checksEnabled: false
  - name: p2p
    port: 8052
    targetPort: 6335
    protocol: TCP
    checksEnabled: false

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistence:
  accessModes: [ "ReadWriteOnce" ]
  size: 10Gi

config:
  cluster:
    enabled: true
    p2p:
      port: 6335

snapshotRestoration:
  enabled: false
