apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-gitops-${ENV}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ${GIT_REPO_URL}
  username: ${GIT_USERNAME}
  password: ${GIT_PASSWORD}
  insecure: "true"
