apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.environment.name }}
    environment: {{ .Values.environment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.environment.name }}
      environment: {{ .Values.environment.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.environment.name }}
        environment: {{ .Values.environment.name }}
    spec:
      {{- if eq .Values.environment.name "github" }}
      imagePullSecrets:
        - name: ghcr-secret
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.probes }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
