apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment.name }}-{{ .Values.environment.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.environment.name }}
    environment: {{ .Values.environment.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: fastapi-rag
  selector:
    app: {{ .Release.Name }}-{{ .Values.environment.name }}
