## Global parameters
global:
  kibana:
    auth:
      username: elastic
      password: elastic123

## Kibana parameters
kibana:
  image:
    registry: docker.elastic.co
    repository: kibana/kibana
    tag: 8.10.4
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  config:
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: "http://elasticsearch-http.database:9200"
    elasticsearch.username: ${ELASTICSEARCH_USERNAME}
    elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

service:
  type: LoadBalancer
  port: 5601
