## Common parameters
nameOverride: ""
fullnameOverride: ""

## Labels to apply to all resources
commonLabels: {}

## Annotations to apply to all resources
commonAnnotations: {}

## Service account parameters
serviceAccount:
  create: true
  name: ""
  annotations: {}

## Pod Security Context
podSecurityContext:
  fsGroup: 1000

## Container Security Context
containerSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

## Kibana configuration
kibana:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
